package com.example;

import java.util.Map;
import java.util.logging.Level;

/**
 * Bounded, Java-authored narrative catalog for Tier 2 (identifier-free,
 * narrative-only) scenario cases (postgres-scenario-harness). Deliberately
 * a fixed catalog, not free text accepted from the query string: the
 * "deliberately mismatched vocabulary" between a Postgres narrative and its
 * Tomcat counterpart is meant to be authored by a human (genuine SRE-style
 * cross-system phrasing), not generated by the harness itself, and no
 * arbitrary text should be injectable into a real log file via a query
 * param.
 *
 * Each entry pairs deliberately with a Postgres-side narrative in
 * scenarios/t2-*.json (see scenarios/README.md).
 */
final class ScenarioNarratives {

    record Entry(Level level, String message) {}

    private static final Map<String, Entry> CATALOG = Map.ofEntries(
            // t2-deadlock-vs-lock-exception counterpart
            Map.entry("pessimistic-lock", new Entry(Level.SEVERE,
                    "PessimisticLockException: could not execute batch for order line update")),
            // t2-pool-exhaustion counterpart
            Map.entry("pool-checkout-timeout", new Entry(Level.SEVERE,
                    "unable to acquire JDBC connection from pool: checkout timed out after 30000ms")),
            // t2-disk-full-vs-write-failure counterpart
            Map.entry("order-persist-failure", new Entry(Level.SEVERE,
                    "OrderPersistException: failed to write order snapshot to disk, no space left on target volume")),
            // t2-slow-query-vs-gateway-timeout counterpart
            Map.entry("gateway-read-timeout", new Entry(Level.SEVERE,
                    "SocketTimeoutException: read timed out while waiting for downstream order-pricing service response")),
            // t2-constraint-violation-vs-validation counterpart
            Map.entry("validation-rejected", new Entry(Level.WARNING,
                    "OrderValidationException: order rejected, duplicate SKU entry violates uniqueness constraint")),
            // t2-restart-vs-connection-reset counterpart
            Map.entry("connection-reset", new Entry(Level.SEVERE,
                    "IOException: connection reset by peer while flushing order confirmation to client")),
            // benign noise — t2-negative-unrelated / t2-8 pure-noise filler
            Map.entry("cache-warmed", new Entry(Level.INFO,
                    "order pricing cache warmed successfully, 128 entries loaded")),
            // benign noise — t2-three-hop-chain middle hop / general filler
            Map.entry("inventory-checked", new Entry(Level.INFO,
                    "inventory check completed for order batch, no discrepancies found")));

    static Entry lookup(String name) {
        return CATALOG.get(name);
    }

    private ScenarioNarratives() {
    }
}
